### ISSUE TITLE
Error in Svg.js

### ISSUE THREAD

**Issue by bshyong** [brentvatne/react-native-svg#1]
There are some issues with the statics defined in `svg.js`:

```
    Line: (line) => {
      var { x1, x2, y1, y2, style } = path.props;
      return `<path fill="${fill}" stroke="${stroke}" stroke-width="${strokeWidth}" d="${d}" transform="${transform}"/>`
    }
```

Looks like this refers to Path, not Line, which will throw errors.

https://github.com/brentvatne/react-native-svg/blob/master/Svg.js#L31-L34

**Comment by brentvatne** [comment]
Woops :smile: can you submit a PR? This is an experimental library that I didn't spend much time on so I'm not surprised, but I'd love to come back to it and make it more robust.

**Comment by bshyong** [comment]
:+1: I'll play around with it and contribute PRs along the way—trying to get the barebones example working first.
