### ISSUE TITLE
It looks we cannot publish apps to app store with adding libxmyl2.2.dylib to linked binaries

### ISSUE THREAD

**Issue by ColinUNCG** [brentvatne/react-native-svg#10]
libxmyl2.2.dylib

**Comment by brentvatne** [comment]
@ColinUNCG - darn, sorry to hear that. I just based that requirement off of this: https://github.com/SVGKit/SVGKit#build-the-static-library-automatic because this library leverages SVGKit to do the hard work. Maybe we need to create an issue on there

**Comment by ColinUNCG** [comment]
@brentvatne sure. I'll create an issue on there
