### ISSUE TITLE
Compatibility with React Native 0.6.0+

### ISSUE THREAD

**Issue by JonasJonny** [brentvatne/react-native-svg#12]
Hello Brent.
It looks like this module is not working with newest update.

**Comment by onesime** [comment]
The problem is just a npm version problem. I had to fork the repo and change the package.json requirements for react-native and it works :)

**Comment by JonasJonny** [comment]
Well, please update the repository @brentvatne.
Thank you @onesime for your fast reply.

**Comment by brentvatne** [comment]
@JonasJonny - bumped in 0.2.1 to >=0.4.4, will give you some annoying issues with peerDependencies on rc's still though - bug report filed here for that one: https://github.com/npm/npm/issues/8854
