### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by aksonov** [brentvatne/react-native-svg#14]
Looks like it parses svg string in runtime, is it possible to avoid that by bridge between svg elements and React elements directly? So each element will render himself and no time spent on serialization?

**Comment by brentvatne** [comment]
It would be nice to optimize this, do you have any time to look into it? A PR is welcome!

**Comment by aksonov** [comment]
I did something, but found also that svgkit is not so accurate for text, so I used SVGgh and did direct creation of svg tags without parsing/serialization. So PR is useless because code base is completely different. Maybe I will create separate package, but not sure about name.

Pavel.

**Comment by aksonov** [comment]
I've published https://github.com/aksonov/react-native-svg-elements as alpha version, maybe you could take a look. I didn't want to introduce one more react native SVG package, but as you can see from my code, PR was not possible (because different SVG rendering library is used). Advantages - no XML parsing, usage of React Native elements _inside_ SVG document.
