### ISSUE TITLE
No manager class found for view with module name "RNSvg"

### ISSUE THREAD

**Issue by jbhatab** [brentvatne/react-native-svg#3]
Just tried to setup D3 charts on my react native app and got this error.

[tid:com.facebook.ReactKit.ShadowQueue][RCTUIManager.m:738] No manager class found for view with module name "RNSvg"

Not entirely sure what it is. I just copied the project and fixed the require files to work in my project.

**Comment by brentvatne** [comment]
heya @jbhatab - did you include RVNSVG.xcodeproj and link the binary?

**Comment by jbhatab** [comment]
ahh sorry. Didn't realize I had to do that. I just included the RVNSVG.xcodeproj in the libraries, but what do I need to include in the 'Link Binaries With Libaries' section? I tried adding the libRNSVG.a but it failed when I did that.

**Comment by jbhatab** [comment]
sorry for my xcode newbiness. Not sure if this has to do with svgkit too? Like do I need to add that to the library stuff.

**Comment by brentvatne** [comment]
Hm that should be compiled for you, what error are you getting?

**Comment by jbhatab** [comment]
I don't know where you even see the errors for xcode for that stuff. I'll play around with it more at work tomorrow. Could it be dependency issues?

And is that all you need to do? Justload the RVNSCG.xcodeproj into the libraries and put the libRNSVG.a in the 'Link Binaries With Libraries'?

**Comment by jbhatab** [comment]
Got the error.

/Users/blaine/dev/native/evueIOS/node_modules/react-native-svg/Libraries/RNSvg.m:3:9: 'SVGKit/Source/SVGKit.h' file not found

So it is related to the SVGkit thing.

**Comment by brentvatne** [comment]
@jbhatab - ah, probably the path relative to your project is different from what is referenced in RNSvg. I haven't tested this outside of the example project so you will probably have to fix the references, or just pull everything into your project without using npm. I unfortunately don't have time for the next couple of days to work on that but if you can wait until Friday I can give you a hand!

**Comment by jbhatab** [comment]
I'll keep playing with it and try to fix things. If I don't get it by Friday then I'd love some help. And I'm down to put some stuff in the readme after I conclude stuff.

**Comment by chroth7** [comment]
@jbhatab : I had similar problems at first, maybe these following steps can help you (I am no expert in xcode etc., so I wanted somebody to double check it before adjusting the readme - so let me know if it works for you). So here's what I did:

1. git clone source
2. npm install (in root directory, to get jsdom-jscore)
3. npm install (in ./Libraries to get react-native for RNSVG (alternatively, you could try to fix the Header Search Paths in xCode, I believe...))
4. cd into ./Libraries/SVGKit (folder should be there already) and then "git clone https://github.com/SVGKit/SVGKit.git"
5. Clean project in xCode
6. Build & Run

Let me know if that does the trick for you... and I am sure there must be a shorter way...
Hope that helps!

**Comment by jbhatab** [comment]
Great thank you. I think step 4 is what I need to do because the svgkit folder was just empty for me. I'll get to it when I can, but I obviously have a whole other breaking issue with react native O.o.

**Comment by jbhatab** [comment]
Tried copying your instructions just to get the example project working at least. Got this error relating to SVGKit. Might just be on me but might was well put it up to get through all the potential errors with setup.

/Users/blaine/dev/native/react-native-svg/Libraries/SVGKit/Source/SVGKit.h:20:9: 'DOMHelperUtilities.h' file not found

**Comment by jbhatab** [comment]
Woop Woop. So I initially cloned the SVGKit repo into the SVGKit folder but I had to move stuff up one because it was SVGKit/SVGKit/<stuff>. But I had to explicitly clean the project again to get things working.

Didn't know you had to reclean things like that.

**Comment by brentvatne** [comment]
:smile: - good stuff, glad you got it working. Will be adding support for [REM](https://github.com/ReactExtensionManager/rem) soon which should make this easier!

**Comment by jbhatab** [comment]
Finally got it setup on my own project too! I think I'm gonna make a template and if I feel super ambitious a screencast.

**Comment by janroesner** [comment]
@brentvatne I went with the same approach and failed with SVKkit.h missing at first. Then I followed the advice up here and eventually got rid of compile errors. Nevertheless when I integrate your excamples wave or reactlogo, the only thing that renders is a black background, and a fixed size rectangle with a 1px red outline. Any suggestions?

**Comment by unknownexception** [comment]
> cd into ./Libraries/SVGKit (folder should be there already) and then "git clone https://github.com/SVGKit/SVGKit.git"

The same. I think README is incomplete — you don't get installed SVGKit from npm.

**Comment by janroesner** [comment]
I think the documentation has to be updated. SVGKit has to be inside the Library Folder or softlinked. The Problem is, that everytime I do  `npm install|update` the softlink is lost. What about integrating SVGKit as submodule and extend the docs accordingly?

**Comment by brentvatne** [comment]
@janroesner @unknownexception - can either of you update the README and send a PR?
